---
- name: Install Docker
  hosts: ubuntu
  become: yes
  tasks:
  - name: ping check
    ping:

  - name: Install packages required for Docker
    apt:
      name: "{{ item  }}"
      state: present
    with_items:
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

  - name: Remove old folder for GPG key
    shell: rm -r /etc/apt/keyrings

  - name: Creater folder for GPG key
    shell: mkdir -p /etc/apt/keyrings

  - name: Add Docker’s official GPG key
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

  - name: Set up the stable repository
    become: yes
    shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  - name: Update repository
    become: yes
    apt:
      update_cache: yes

  - name: Install Docker
    become: yes
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - docker-compose

  - name: Start Docker
    become: yes
    shell: systemctl enable docker

  - name: Check status Docker
    become: yes
    shell: systemctl status docker