---
- name: Uninstall tools 
  hosts: local
  tasks:
    - name: Uninstall curl
      become: yes
      apt:
        name: curl
        state: absent
    
    - name: Uninstall ufw
      become: yes
      apt:
        name: ufw
        state: absent