---
- name: Install NGINX
  hosts: ubuntu
  tasks:
    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes

    - name: Install nginx
      become: yes
      apt:
        name: nginx
        state: present

    - name: Check if nginx is running
      command: systemctl status nginx
      register: nginx_status