---
- name: Remove virtual host
  hosts: ubuntu
  become: true
  vars:
    site_name: "{{ site_name }}"

  tasks:
    - name: Remove virtual host configuration file
      file:
        path: "/etc/nginx/sites-available/{{ site_name }}"
        state: absent
      ignore_errors: yes

    - name: Remove symbolic link from sites-enabled
      file:
        path: "/etc/nginx/sites-enabled/{{ site_name }}"
        state: absent
      ignore_errors: yes
    
    - name: Restart NGINX service
      service:
        name: nginx
        state: restarted
