---
- name: connectivity check
  hosts: ubuntu
  tasks:
  - name: ping check
    ping:

  - name: echo hello
    command: echo hello world
    register: result

  - name: print the result
    debug: msg="{{ result.stdout }}"

