---
- name: Install k3s
  hosts: local
  tasks:
  - name: ping check
    ping:

  - name: Install k3s
    become: yes
    shell: curl -sfL https://get.k3s.io | sh -

  - name: Check k3s status
    command: systemctl status k3s
    register: k3s_status

  - name: Check k3s status
    debug: msg={{ k3s_status.stdout }}

  - name: Permission to access k3s
    become: yes
    shell: chmod +r /etc/rancher/k3s/k3s.yaml

  - name: Open port to access k3s
    become: yes
    shell: ufw allow 6443/tcp
